apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: mahshaker/udagram-api-feed:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udacity-p3-env-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: udacity-p3-env-config
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: udacity-p3-env-config
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udacity-p3-env-config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udacity-p3-env-config
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: udacity-p3-env-config
              key: JWT_SECRET
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udacity-p3-env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udacity-p3-env-secret
              key: POSTGRES_PASSWORD
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: udacity-p3-env-config
              key: URL
        volumeMounts:
        - name: udacity-p3-aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      volumes:
      - name: udacity-p3-aws-secret
        secret:
          secretName: udacity-p3-aws-secret


